Repository unknown2k21/Charity, pull requests merged in 2022-10, with the labels that each got.

#1 Index
  index.html
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#2 stylesheet
  css/animate.css
  css/bootstrap.css
  css/icomoon.css
  css/style.css
  css/superfish.css
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 Images
  images/contact.jpg
  images/cover_bg_1.jpg
  images/cover_bg_10.jpg
  images/cover_bg_11.jpg
  images/cover_bg_12.jpg
  images/cover_bg_2.jpg
  images/cover_bg_3.jpg
  images/cover_bg_4.jpg
  images/cover_bg_5.jpg
  images/cover_bg_6.jpg
  images/cover_bg_7.jpg
  images/cover_bg_8.jpg
  images/cover_bg_9.jpg
  images/loc.png
  images/person_2.jpg
  images/person_3.jpg
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 updated the main page
  index.html
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#6 Update README.md
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted
